#!/bin/bash
# Narration text extracted from script.md
# Run generate_audio.sh to produce MP3s

SLIDE_1="What if someone with an intellectual disability could work a real job without a handler standing next to them? Not someday. Now. Brian's got the skills. He's got the will. What he's been missing is a coach who's always available, always consistent, and doesn't cost more than his paycheck. We built an AI job coach that runs right on the glasses he already wears. No cloud dependency. No surveillance. Just Brian, the task, and the support he needs the moment he needs it."
SLIDE_2="Here's the gap: 5.4 million adults with intellectual disabilities in the United States. Less than one in five has a job. Not because they can't work. Most of them can. The problem is job coaching doesn't scale. A disability support professional—a DSP—costs twenty-five, thirty, forty dollars an hour, and there aren't enough of them. They burn out. They move on. And the coaching is only as good as whoever's on shift that day. Meanwhile, the assistive technology that people with disabilities rely on? It's stuck in the past. It's single-purpose. It's expensive. It's stigmatizing. And way too much of it records everything to the cloud, which means Brian's privacy goes with it. The technology we use every day has gotten so smart. Why hasn't the technology for people with disabilities kept up?"
SLIDE_3="We built a job coach that runs on the edge—meaning right there on the device, with no cloud dependency, no constant surveillance. It does three things. First, task coaching: a DSP records the steps for a job—how to stock a shelf, how to clean a restroom, how to bag groceries—and Brian can replay that sequence anytime, at his own pace. Second, danger steering: the camera on the glasses watches for safety issues in real time and alerts him before something goes wrong. Third, social navigation: if Brian's not sure what to say when he's ordering food or checking out, the system gives him a script—a coach in his ear, no one else hears it. Everything runs locally. Brian's data stays with Brian. No cloud surveillance. No data broker selling his behavior to the highest bidder."
SLIDE_4="Here's what that looks like in practice. Brian wears Meta Ray-Ban glasses: camera, microphone, bone conduction audio. On the device side—this could be a small edge server, could be a handheld—we run an open-source operating system from Red Hat, IBM's Granite AI model for understanding context, and Watson for converting speech to text and text back to speech. All of that lives on the device. When Brian's connected, the system talks to our backend on SAP BTP—that's the task library, the analytics so we know what's working, and the interface for disability support professionals to design new coaching sequences. The architecture is built for offline-first operation, which means if the connection drops, coaching doesn't stop."
SLIDE_5="Now, the coaching gets smarter over time, but not the way you might think. We don't claim that the system learns automatically from Brian's usage—that's not how this works. Here's what actually happens. We observe how people like Brian use the coaching. When we notice a pattern—like a task sequence that confuses multiple people—we identify what needs improvement. Our team refines the task prompts, tests the new version, and pushes it out via an atomic image update. If the new version works better, great. If not, we roll back in seconds. What's powerful here is that we can identify problems from the field and ship improvements in a week, not a quarter. And because every update is atomic and reversible, we never leave a customer stuck with a broken model. Safety and speed, both at once."
SLIDE_6="Let's walk through what Brian actually experiences. He's stocking shelves at a retail job, and here's how the coaching works. [The sequence appears] "Pick up the box from the cart." He does. "Find the product tag on the shelf—it matches the box label." Now he's searching, actively, for the right spot. "Place items on the shelf, left to right, labels facing forward." That's where we are now. "Move the empty box to the recycling bin near the back door." And finally, "Great work. Ready for the next box?" This is a mockup we built to show the user experience. The task sequence is real—a DSP recorded it once, months ago. Brian can replay it anytime, at his own pace. He can pause on any step. He can back up if he made a mistake. No timer. No DSP waiting. Just him and the work."
SLIDE_7="To prove we've actually built this, we created a live browser demo you can interact with right now. It's called Brian Chores. It's running edge text-to-speech using the same Jenny Neural voice you're hearing right now, it's offline-capable, and it's running the actual task playback pipeline from our system. So in a moment, you're going to see and hear the real thing working, not a mockup. Let me show you."
SLIDE_8="So here's what this is really about. Not a new feature. Not a nice-to-have. Independence. Dignity. Determination. Five and a half million adults with intellectual disabilities in the United States. Less than twenty percent have jobs. Not because they can't do the work. Because the support doesn't scale. This changes that. Brian gets the coaching he needs. When he needs it. Where he needs it. No handler. No surveillance. No waiting for a DSP who might not show up. For people with disabilities, this is the difference between sitting on the sidelines and being in the game. Let's talk about how to get this into the field."
