#!/bin/bash
# new_session.sh — print a sync-up summary ready to paste into a new AI conversation.
# Output is clean markdown. Copy the whole thing and paste it to re-orient Zoe fast.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CHANGELOG="$REPO_DIR/STATE/CHANGELOG.md"
TODO="$REPO_DIR/STATE/TODO.md"
MAILBOX="$REPO_DIR/STATE/MAILBOX.md"
ENVIRONMENT="$REPO_DIR/STATE/ENVIRONMENT.md"
TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

GIT_USER=$(git -C "$REPO_DIR" config user.name 2>/dev/null || git config --global user.name 2>/dev/null || echo "unknown")

# --- Tier detection ---
# A = terminal AI with direct file access (running in a terminal right now)
# B = chat AI with browsing capability (cannot detect from script; default for non-terminal)
# C = chat AI without browsing (cannot detect from script; conservative fallback)
# Since this script runs in a terminal, the output is always tier A at generation time.
# The tier field tells the receiving AI what context this blob was generated from.
if [ -t 1 ]; then
    TIER="A"
else
    TIER="A"
fi

# --- Helper: extract last N timestamped entries from a file ---
# Entries must start with "- YYYY-MM-DD" format
last_entries() {
    local file="$1"
    local count="$2"
    if [ ! -f "$file" ]; then
        echo "_No file found at $file_"
        return
    fi
    local result
    result=$(grep -E '^- [0-9]{4}-[0-9]{2}-[0-9]{2}' "$file" | tail -n "$count")
    if [ -z "$result" ]; then
        echo "_No entries yet._"
    else
        echo "$result"
    fi
}

# --- Helper: extract sections with active items ---
active_section() {
    local file="$1"
    local section="$2"
    if [ ! -f "$file" ]; then
        echo "_No file found at $file_"
        return
    fi
    # Print lines between the section header and the next ## header
    awk "/^## $section/{found=1; next} found && /^## /{found=0} found" "$file" \
        | grep -v '^\s*$' \
        | grep -v '^<!--' \
        || echo "_No items in $section._"
}

cat <<SYNC
<!-- zoe-sync-v1 | tier:$TIER | generated:$TS -->
---
## Zoe Sync-Up — $TS
**User:** $GIT_USER
**tier:** $TIER
**generated:** $TS

Paste this block at the start of a new conversation to re-orient Zoe.

---

### Last 5 Changelog Entries

$(last_entries "$CHANGELOG" 5)

---

### Current TODO

**Active:**
$(active_section "$TODO" "Active")

**Backlog:**
$(active_section "$TODO" "Backlog")

---

### Open Mailbox Items

$(active_section "$MAILBOX" "Active threads")

---

### Environment (summary)

$(if [ -f "$ENVIRONMENT" ]; then
    grep -E "^- (Git user|OS|Shell|Working directory):" "$ENVIRONMENT" || grep -E "^(Last updated|## Who|## OS)" "$ENVIRONMENT" | head -6
else
    echo "_Run \`bash SCRIPTS/update_state.sh\` to generate environment snapshot._"
fi)

---
*Generated by \`SCRIPTS/new_session.sh\` — source of truth is \`STATE/\`*
<!-- /zoe-sync-v1 -->
SYNC
